### ISSUE TITLE
"GL_INVALID_OPERATION error generated. No active compute shader."

### ISSUE THREAD

**Issue by pdblood** [tobspr/RenderPipeline#103]
I installed the latest master branch of render pipeline and the latest development version of Panda3D for windows. It seems that OpenGL shaders will not compile on my Windows system running the latest NVIDIA drivers. I get this error:

```
fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
```

See the example below:
```
C:\Panda3D-1.10.0-x64\RenderPipeline-master\RenderPipeline-master\samples\01-Material-Demo>C:\Panda3D-1.10.0-x64\python\python.exe main.py
[>] CORE                      Using panda3d-supplied core module
[>] RenderPipeline            Using Python 3.6 with architecture win_amd64
[>] RenderPipeline            Using Panda3D 1.10.0 built on Sep  9 2018 15:09:21
[>] RenderPipeline            Using git commit 47496068d33de66ea479168b78501305bf63fe49
[>] MountManager              Auto-Detected base path to /c/Panda3D-1.10.0-x64/RenderPipeline-master/RenderPipeline-master
[>] RenderPipeline            Mount manager was not mounted, mounting now ...
[>] MountManager              Setting up virtual filesystem
[>] MountManager              Mounting auto-detected config dir: /c/Panda3D-1.10.0-x64/RenderPipeline-master/RenderPipeline-master/config/
[>] MountManager              Mounting ramdisk as /$$rptemp
[>] RenderPipeline            No settings loaded, loading from default location
Known pipe types:
  wglGraphicsPipe
(all display modules loaded.)
[>] RenderPipeline            Driver Version = 4.3.0 NVIDIA 399.24
[>] RenderPipeline            Driver Vendor = NVIDIA Corporation
[>] RenderPipeline            Driver Renderer = GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2
[>] RenderPipeline            Render resolution is 800 x 600
[>] LightManager              Tile size = 24 x 16 , Num tiles = 34 x 38
[>] GPUCommandQueue           Allocating command buffer of size 32768
[>] GroupedInputBlock         Native UBO support = False
[!] RPLoader                  Loading '/$$rp/data/default_cubemap/cubemap.txo' took 178.62 ms
[>] PluginManager             Loading plugin settings
[>] PluginManager             Creating plugin instances ..
[>] Debugger                  Creating debugger
[>] plugin:scattering         Loading scattering method for 'eric_bruneton'
[>] StageManager              Setup stages ..
[>] StageManager              Preparing stages ..
[>] AOStage                   Blur quality is MEDIUM
[>] StageManager              Awaiting future pipe Exposure
[>] UpdatePreviousPipesStage  Creating previous pipes stage ..
[>] StageManager              Writing shader config
[>] plugin:pssm               Initializing pssm ..
[>] ScatteringMethodEricBruneton Precomputing ...
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/transmittance.compute.glsl:
(1093) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/delta_e.compute.glsl:
(1091) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/delta_sm_sr.compute.glsl:
(1092) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/copy_irradiance.compute.glsl:
(1095) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/copy_inscatter.compute.glsl:
(1094) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/delta_j.compute.glsl:
(1097) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/irradiance_n.compute.glsl:
(1096) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/delta_sr.compute.glsl:
(1093) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/add_delta_e.compute.glsl:
(1097) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
:display:gsg:glgsg(error): GL_INVALID_OPERATION error generated. No active compute shader.
:display:gsg:glgsg(error): An error occurred while compiling GLSL compute shader /$$rp/rpplugins/scattering/shader/eric_bruneton/add_delta_sr.compute.glsl:
(1097) : fatal error C9999: *** exception during compilation ***
:display:gsg:glgsg(error): An error occurred while linking GLSL shader
[>] RenderPipeline            Finished initialization in 4.346 s, first frame: 3
[>] RenderPipeline            Took 0.783 s until first frame
```

**Comment by x86games** [comment]
Same error here. Latest Nvidia Drivers, Nvidia Geforce 1060. 
Only via Intel 630 integrated card, it works (with very bad performance of course)

Any way to fix that serious issue?

**Comment by bluekyu** [comment]
I found this issue is caused by commit https://github.com/tobspr/RenderPipeline/commit/07e81a29f69081cdb6e6c999cbbc795fc4438e9c

NVIDIA vendor string is "NVIDIA corpor**ati**on", however the string has "ati" substring.
So, `IS_AMD` macro is "1" and `RESTRICT` macro has `strict` keyword.
It raises shader compilation error. (I can see this error in OpenGL 4.6, not 4.3 in config.prc)

I think the below codes should be cleared up:
https://github.com/tobspr/RenderPipeline/blob/52f1371b781ab8ad1f042747cc631bd95e3c4878/rpcore/render_pipeline.py#L588-L591
(But I don't know AMD version string, so I did not create PR.)

**Comment by bluekyu** [comment]
I checked that `get_driver_vendor()` uses `GL_VENDOR` query of OpenGL.
So, for AMD GPU, it may return "ATI Technologies Inc".
And "NVIDIA Corporation" for NVIDIA GPU, "Intel Open Source Technology Center" or "Intel Inc" for Intel GPU.

**Comment by rdb** [comment]
For what it's worth, here's a database of all possible vendor values in the wild:
http://feedback.wildfiregames.com/report/opengl/feature/GL_VENDOR

**Comment by x86games** [comment]
My Nvidia returns "nvidia corporation" here as vendor, so the definition in render_pipeline.py should be correct. I also see no difference in https://github.com/tobspr/RenderPipeline/commit/07e81a29f69081cdb6e6c999cbbc795fc4438e9c that can cause the issue.

Anyone figured out which is the last stable version of RenderPipeline that works with Nvidia cards?

**Comment by rdb** [comment]
@bluekyu is right.  @x86games, if you look carefully, you'll see that "nvidia corpor**ati**on" contains "ati", and so both `IS__NVIDIA` and `IS_AMD` get set to true on NVIDIA hardware, which causes the check after 07e81a29f69081cdb6e6c999cbbc795fc4438e9c to evaluate differently on NVIDIA hardware.

So, to answer your question, the last version that should work on NVIDIA hardware is the one before that, which is ec49f7121c2c7722a2c299e07019853ded961101.

**Comment by x86games** [comment]
> 
> 
> @bluekyu is right. @x86games, if you look carefully, you'll see that "nvidia corpor**ati**on" contains "ati", and so both `IS_NVIDIA` and `IS_AMD` get set to true on NVIDIA hardware, which causes the check after [07e81a2](https://github.com/tobspr/RenderPipeline/commit/07e81a29f69081cdb6e6c999cbbc795fc4438e9c) to evaluate differently on NVIDIA hardware.
> 
> So, to answer your question, the last version that should work on NVIDIA hardware is the one before that, which is [ec49f71](https://github.com/tobspr/RenderPipeline/commit/ec49f7121c2c7722a2c299e07019853ded961101).
> 
> I have created PR #104 that should theoretically fix this issue.

@rdb: Now I got it. That was quite obvious, indeed.
